"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def next_fib(fib1, fib2):
    return fib1 + fib2

fib1 = 1
fib2 = 2
total = 2
while True:
    new_fib = next_fib(fib1, fib2)
    if new_fib > 4 * 10 ** 6:
        break

    if new_fib % 2 == 0:
        total += new_fib
    (fib1, fib2) = (fib2, new_fib)
print total
